// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKQITJBOhpcJLm-qWZv7xz-B0j3jaVVcw',
    appId: '1:908175346333:web:becd756867ebd311a4e274',
    messagingSenderId: '908175346333',
    projectId: 'fruit-hub-7c37b',
    authDomain: 'fruit-hub-7c37b.firebaseapp.com',
    storageBucket: 'fruit-hub-7c37b.firebasestorage.app',
    measurementId: 'G-0DF0H505Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA799fKAMjKRdimBcMZrWLlF0UjX9_eOQ',
    appId: '1:908175346333:android:72a73cc37c97e308a4e274',
    messagingSenderId: '908175346333',
    projectId: 'fruit-hub-7c37b',
    storageBucket: 'fruit-hub-7c37b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkI5edYBeAaVXeKRZBnUJ57B76S2uI8xI',
    appId: '1:908175346333:ios:119ceca40065520aa4e274',
    messagingSenderId: '908175346333',
    projectId: 'fruit-hub-7c37b',
    storageBucket: 'fruit-hub-7c37b.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkI5edYBeAaVXeKRZBnUJ57B76S2uI8xI',
    appId: '1:908175346333:ios:119ceca40065520aa4e274',
    messagingSenderId: '908175346333',
    projectId: 'fruit-hub-7c37b',
    storageBucket: 'fruit-hub-7c37b.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKQITJBOhpcJLm-qWZv7xz-B0j3jaVVcw',
    appId: '1:908175346333:web:5aa0abfbf06ff48ca4e274',
    messagingSenderId: '908175346333',
    projectId: 'fruit-hub-7c37b',
    authDomain: 'fruit-hub-7c37b.firebaseapp.com',
    storageBucket: 'fruit-hub-7c37b.firebasestorage.app',
    measurementId: 'G-G3ZSXKRDYV',
  );
}
